import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vikash Denzil Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/PortfolioFavicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My portfolio site is under development, please be patient! Meanwhile checkout <a href="https://haloweave.com">haloweave!</a>
        </h1>
      </main>
    </div>
  )
}
